version: '3.4'
services:
  postgresql:
    image: postgres:14-alpine3.15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: "projeto-messagechannel"
    ports:
      - 5432:5432
    networks:
      backend:
  java:
    image: rafaelsulimann/projeto-weon:1.1
    container_name: chat-message-com-spring
    restart: always
    environment:
      DATABASE_URL: "jdbc:postgresql://postgresql:5432/projeto-messagechannel"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234567"
      POSTGRES_DB: projeto-messagechannel
    ports:
      - 8080:8080
    links:
      - postgresql
    depends_on:
      - postgresql
    networks:
      backend:
networks:
  backend: